 #orchestration/
#│   │-- helm/
#│   │   │-- Chart.yaml
#│   │   │-- values.yaml
#│   │   │-- templates/
#│   │       │-- deployment.yaml
#│   │       │-- service.yaml
#│   │-- k8s-manifests/
#│   │   │-- deployment.yaml
### Helm Chart for Kubernetes Deployment (orchestration/helm/templates/deployment.yaml)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tecx-dsp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tecxdsp
  template:
    metadata:
      labels:
        app: tecxdsp
    spec:
      containers:
      - name: tecx-dsp
        image: my-registry/tecx-dsp:latest
```

