apiVersion: apps/v1
kind: Deployment
metadata:
  name: tecx-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/hitech/backend:latest
          ports:
            - containerPort: 8080
