apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    storage:
      backend: local
      local:
        path: /var/tempo
